### ISSUE TITLE
Is there any reference paper/resource for more details?

### ISSUE THREAD

**Issue by Abhijeet-Das** [ehart-altair/SimpsonsParadox#1]
Thanks for putting the efforts and explaining the Simpsons Paradox. I am researcher at Fraunhofer Institute, Germany. I was wondering do you have any research paper published or resource or blog to understand the process of detecting Simpsons Paradox using regression model. I have gone through the references but didnt find any detailed algorithmic approach. I would like to code something similar in R so a better understanding of both the approaches (building decision trees and regression models) would be very much useful.
Thanks

**Comment by ehart-altair** [comment]
Hi Abhijeet, thanks for your response! (Sorry I was a bit slow to reply).
We didn't write a paper to accompany this work. However, maybe I can help a bit with some additional information:

1. We did write a blog explaining a bit about our work. You can find it here: https://blog.altair.com/defining-simpsons-paradox-and-how-to-automatically-detect-it/

2. At the start of our research project we relied on this paper to help get oriented in this space: https://arxiv.org/abs/1801.04385

3. The authors of that paper also published some code on Github, which you can find here: https://github.com/ninoch/Trend-Simpsons-Paradox

4. The general idea for looking for Simpson's Paradox with regression models might look something like this:
Say you have a DV Y, an IV X, and a condfounding variable Z:

- Build a model Y ~ X
- Build another model Y ~ X+Z
- Look at the coefficient of X in each model. If it has opposite signs in the 2 models, that's an indication of Simpson's Paradox.
(There are a bunch of details that will come up if you try to do this, but this is a good start).

I hope that helps to start. Feel free to reach out if you have other questions!
